version: '3'

services:

#App
  server:
    build: docker
    container_name: laravel
    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:/application:cached

#DB
  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - 3306:3306
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql:cached

#WEB
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:8000"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ${APP_PATH_HOST}:/application:cached
    depends_on:
      - server

#Redis
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
